<?php

namespace Alura\Banco\Modelo\Conta;

class ContaPoupanca extends Conta
{
    protected function getPercentualTarifa(): float
    {
        return 0.03; // TODO: Change the autogenerated stub
    }

    private function transferir(float $valorATransferir, ContaPoupanca $contaDestino): void
    {
        if ($valorATransferir > $this->saldo) {
            echo 'Saldo indisponível';
            return;
        }

        $this->sacar($valorATransferir);
        $contaDestino->saldo += $valorATransferir;
    }
}