<?php

namespace Alura\Banco\Modelo\Conta;

class ContaCorrente extends Conta
{
    protected function getPercentualTarifa(): float
    {
        return 0.05; // TODO: Change the autogenerated stub
    }
}